export const CONNECT_USER = 'CONNECT_USER';
export const DISCONNECT_USER = 'DISCONNECT_USER';
export const SWITCH_USER = 'SWITCH_USER';
export const ADD_OPERATOR = 'ADD_OPERATOR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
